spring.application.name=pizzashop
spring.datasource.url=jdbc:mysql://localhost:3306/pizza_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Hariom@6447
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true